theme = "catppuccin_mocha"

[editor]
line-number = "relative"
# Show currently open buffers, only when more than one exists.
bufferline = "multiple"
# Highlight all lines with a cursor
cursorline = true
# Show a ruler at column 120
rulers = [120]
# Force the theme to show colors
true-color = true

[editor.cursor-shape]
insert = "bar"
[editor.indent-guides]
character = "╎"
render = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

# Zelllij
[keys.normal.";"]
# Interactive search in current working directory
l = ":pipe-to helix-zellij search --current"
## Interactive search in current working directory (include path name in the search)
L = ":pipe-to helix-zellij search --current-inc-path"
## Interactive search in current git directory
w = ":pipe-to helix-zellij search --workspace"
## Interactive search in current git directory (include path name in the search)
W = ":pipe-to helix-zellij search --workspace-inc-path"
## Interactive search in current buffer
B = ":pipe-to helix-zellij search --buffer"
## Git status
s = ":pipe-to helix-zellij git --status"
## Git blame
b = ":pipe-to helix-zellij git --blame"
## Git browse github repo using default browser
H = ":pipe-to helix-zellij git --browse"
## lazygit
g = ":pipe-to helix-zellij git --lazygit"
## Diff current buffer with content on disk
d = ":pipe-to helix-zellij diff"

[editor.file-picker]
hidden = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)
