theme = "Catppuccin-macchiato"
client_id = "91d19ef8c9ac47f6955cb51f5422f639"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
track_table_item_max_len = 32
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
playback_window_width = 6
enable_media_control = true
enable_streaming = true
enable_cover_image_cache = true
default_device = "spotify-player"

[copy_command]
command = "xclip"
args = [
    "-sel",
    "c",
]

[device]
name = "spotify-player"
device_type = "speaker"
volume = 50
bitrate = 320
audio_cache = false
